export declare const kAvvioBoot: unique symbol
export declare const kChildren: unique symbol
export declare const kServerBindings: unique symbol
export declare const kBodyLimit: unique symbol
export declare const kSupportedHTTPMethods: unique symbol
export declare const kRoutePrefix: unique symbol
export declare const kLogLevel: unique symbol
export declare const kLogSerializers: unique symbol
export declare const kHooks: unique symbol
export declare const kContentTypeParser: unique symbol
export declare const kState: unique symbol
export declare const kOptions: unique symbol
export declare const kDisableRequestLogging: unique symbol
export declare const kPluginNameChain: unique symbol
export declare const kRouteContext: unique symbol
export declare const kGenReqId: unique symbol
export declare const kHttp2ServerSessions: unique symbol
export declare const kSchemaController: unique symbol
export declare const kSchemaHeaders: unique symbol
export declare const kSchemaParams: unique symbol
export declare const kSchemaQuerystring: unique symbol
export declare const kSchemaBody: unique symbol
export declare const kSchemaResponse: unique symbol
export declare const kSchemaErrorFormatter: unique symbol
export declare const kSchemaVisited: unique symbol
export declare const kRequest: unique symbol
export declare const kRequestPayloadStream: unique symbol
export declare const kRequestAcceptVersion: unique symbol
export declare const kRequestCacheValidateFns: unique symbol
export declare const kRequestOriginalUrl: unique symbol
export declare const kFourOhFour: unique symbol
export declare const kCanSetNotFoundHandler: unique symbol
export declare const kFourOhFourLevelInstance: unique symbol
export declare const kFourOhFourContext: unique symbol
export declare const kDefaultJsonParse: unique symbol
export declare const kReply: unique symbol
export declare const kReplySerializer: unique symbol
export declare const kReplyIsError: unique symbol
export declare const kReplyHeaders: unique symbol
export declare const kReplyTrailers: unique symbol
export declare const kReplyHasStatusCode: unique symbol
export declare const kReplyHijacked: unique symbol
export declare const kReplyStartTime: unique symbol
export declare const kReplyNextErrorHandler: unique symbol
export declare const kReplyEndTime: unique symbol
export declare const kReplyErrorHandlerCalled: unique symbol
export declare const kReplyIsRunningOnErrorHook: unique symbol
export declare const kReplySerializerDefault: unique symbol
export declare const kReplyCacheSerializeFns: unique symbol
export declare const kTestInternals: unique symbol
export declare const kErrorHandler: unique symbol
export declare const kErrorHandlerAlreadySet: unique symbol
export declare const kChildLoggerFactory: unique symbol
export declare const kHasBeenDecorated: unique symbol
export declare const kKeepAliveConnections: unique symbol
export declare const kRouteByFastify: unique symbol
