export const kRoutePrefix: unique symbol
export const kSupportedHTTPMethods: unique symbol
export const kLogLevel: unique symbol
export const kLogSerializers: unique symbol
export const kHooks: unique symbol
export const kSchemaController: unique symbol
export const kOptions: unique symbol
export const kReplySerializerDefault: unique symbol
export const kReplyIsError: unique symbol
export const kRequestPayloadStream: unique symbol
export const kDisableRequestLogging: unique symbol
export const kSchemaErrorFormatter: unique symbol
export const kErrorHandler: unique symbol
export const kHasBeenDecorated: unique symbol
export const kRequestAcceptVersion: unique symbol
export const kRouteByFastify: unique symbol
export const kRouteContext: unique symbol
export const kFourOhFourContext: unique symbol
export const kReply: unique symbol
export const kRequest: unique symbol
export const kBodyLimit: unique symbol
export const kContentTypeParser: unique symbol
export const kRequestCacheValidateFns: unique symbol
export const kReplyCacheSerializeFns: unique symbol
export const kChildLoggerFactory: unique symbol
